### ISSUE TITLE
Create a basic external subscriber to hook up to nuklaivm

### ISSUE THREAD

**Issue by kpachhai** [Nuklai/nuklaivm#67]
With the new version of nuklaivm, it is now possible to have an external server constantly getting fed about each and every transaction and each and every block. This means that we can utilize our external server to store up the historical data(as the indexer of the vm can only store a very limited amount of blocks in memory - default is 1024 blocks of historical data). 

To transform our external subscriber into a full historical node, we can take several steps to ensure it captures, organizes, and indexes blockchain data effectively:

### 1. **Storage and Database Design**
   - **Select a Database**: For a historical node, a database that supports quick indexing and retrieval of data is essential. For example:
     - **Relational Databases (PostgreSQL, MySQL)**: Suitable if you need structured, ACID-compliant storage with complex query capabilities.
     - **NoSQL Databases (MongoDB, Cassandra)**: Helpful for document-based storage and high scalability, particularly with JSON-like structures.
     - **Time-Series Databases (InfluxDB, TimescaleDB)**: Useful if there’s a need to manage historical data with time as a key component.

   - **Define Schema**:
     - **Blocks**: Store each block’s ID, parent ID, timestamp, height, state root, and any other metadata.
     - **Transactions**: Include transaction ID, sponsor, max fee, and action details.
     - **Actions**: Record action type, associated transaction ID, and parsed fields from action data.
     - **State Changes**: If relevant, capture any changes to balances, assets, or other on-chain states.

   - **Indexing**: Optimize indexing for:
     - **Block Height**: To allow for easy range queries.
     - **Transaction ID**: For transaction-specific lookups.
     - **Action Types**: To retrieve specific actions quickly.

### 2. **Deduplication Mechanism**
   - Set up logic in your subscriber to check whether the block or transaction already exists in the database. You can achieve this by:
     - **Storing Block Hashes**: Before processing a new block, check its hash against stored hashes to avoid duplicates.
     - **Batch Insertion and Updates**: To avoid race conditions with two nodes sending data simultaneously, batch insertions with unique constraints will prevent duplicates and maintain database integrity.

### 3. **Data Processing and Storage Pipeline**
   - **Buffered Ingestion**: Use a buffered queue to handle incoming data from nodes and process it before storing it in the database.
   - **Asynchronous Processing**: Implement background workers for processing transactions and actions within blocks, saving computational time and preventing blocking operations.
   - **Error Handling and Retrying**: For reliability, build in retry mechanisms for failed data insertions or processing steps.

### 4. **Data Access and API Layer**
   - Develop a read-optimized API layer that sits on top of your database:
     - **Endpoints**: Provide endpoints for querying blocks, transactions, actions, and state changes.
     - **Filtering Options**: Allow for queries by block height, transaction ID, action type, and timestamp range.
     - **Pagination and Caching**: Use pagination and caching to handle large data sets efficiently and minimize latency.

### 5. **Backup, Replication, and Maintenance**
   - **Database Backups**: Schedule regular backups to ensure historical data remains intact.
   - **Replication**: Consider replicating the database to handle high-availability requirements and failover support.
   - **Data Compaction and Pruning**: Implement data compaction (especially in NoSQL or time-series databases) to keep the database efficient, periodically removing old or unneeded data if feasible.

### 6. **Monitoring and Scaling**
   - **Metrics Collection**: Track metrics like database read/write performance, API request rates, and node synchronization status.
   - **Auto-Scaling Infrastructure**: To handle increased traffic or data load, set up auto-scaling for your subscriber infrastructure, especially for the database and API services.

This setup will establish a high-performing, full historical node that can handle both real-time data ingestion and efficient querying, providing robust historical data access for our blockchain. 

### Some Use Cases

1. **Blockchain Explorer**: Building a detailed blockchain explorer to provide users with insights into real-time blocks, transactions, and account balances. The subscriber would store historical data, allowing for query capabilities like “last 100 transactions” or “all transactions by a particular address.”

2. **Analytics and Monitoring**: Providing data feeds for network analytics and monitoring tools. Third parties could use this to analyze transaction frequency, token movement, gas usage, validator participation, etc., over time. Analytics platforms could plug into the subscriber to create dashboards and visualize key metrics.

3. **Data Indexing for DApps**: Allowing decentralized applications to query complex data sets, like asset creation events or NFT transfers. DApps could query data directly without relying on blockchain node requests, speeding up retrieval.

4. **Historical Data Archiving**: The external subscriber could maintain a complete history of the blockchain’s states and transactions, allowing researchers, developers, and auditors to retrieve past data. This also facilitates efficient back-testing of strategies for financial applications on the blockchain.

5. **Compliance and Auditing**: Businesses needing compliance data can integrate with the subscriber to retrieve historical transaction data and prove data integrity or retrieve records for auditing.

6. **Event-Triggered Notifications**: By integrating with the subscriber, third-party applications can trigger events, such as sending notifications or executing smart contracts based on predefined criteria (like asset transfers or new block production).

To start implementing the external subscriber, we can break down each task as follows:

### 1. **Setting Up PostgreSQL with TimescaleDB**
   - **Install PostgreSQL** and add **TimescaleDB** as an extension for time-series support. TimescaleDB is well-suited here due to its efficient handling of time-based data, enabling faster queries and better scalability for historical data.
   - **Configuration**: Configure PostgreSQL for optimal performance based on the expected data volume, likely increasing `shared_buffers`, `work_mem`, and other memory settings. We can revisit this configuration after testing initial queries and inserts.

### 2. **Define the Schema**
   We'll create tables with foreign keys, primary keys, and indexes tailored for fast retrieval on block-related fields. Below is a high-level schema design:

   ```sql
   -- Block Table
   CREATE TABLE blocks (
       id SERIAL PRIMARY KEY,
       block_height BIGINT NOT NULL,
       block_hash VARCHAR(64) UNIQUE NOT NULL,
       parent_block_hash VARCHAR(64),
       state_root VARCHAR(64),
       timestamp TIMESTAMPTZ,
       unit_prices JSONB,
       UNIQUE (block_height, block_hash)
   );

   -- Transaction Table
   CREATE TABLE transactions (
       id SERIAL PRIMARY KEY,
       tx_hash VARCHAR(64) UNIQUE NOT NULL,
       block_id INT REFERENCES blocks(id) ON DELETE CASCADE,
       sponsor VARCHAR(64),
       max_fee NUMERIC,
       success BOOLEAN,
       fee NUMERIC,
       outputs JSONB,
       timestamp TIMESTAMPTZ
   );

   -- Actions Table
   CREATE TABLE actions (
       id SERIAL PRIMARY KEY,
       tx_id INT REFERENCES transactions(id) ON DELETE CASCADE,
       action_type SMALLINT,
       action_details JSONB
   );

   -- Indexes for faster querying
   CREATE INDEX idx_block_height ON blocks(block_height);
   CREATE INDEX idx_block_hash ON blocks(block_hash);
   CREATE INDEX idx_tx_hash ON transactions(tx_hash);
   CREATE INDEX idx_sponsor ON transactions(sponsor);
   CREATE INDEX idx_action_type ON actions(action_type);
   ```

   This schema:
   - Links blocks, transactions, and actions with foreign key relationships.
   - Indexes crucial fields to allow quick retrieval by block height, block hash, transaction hash, sponsor, and action type.
   - Stores `unit_prices`, `outputs`, and `action_details` as JSONB for flexibility with structured or nested data.

### 3. **Developing a Read-Optimized API Layer**
   We'll use a web framework like **Gin** (Go) to build RESTful endpoints for data retrieval, handling popular requests with optimized queries.

   **Example Endpoints:**
   - **GET /blocks**: Retrieve blocks, with optional filters for height, timestamp range, and hash.
   - **GET /transactions**: Fetch transactions by transaction hash, sponsor, or block height.
   - **GET /transactions/:tx_hash**: Retrieve a single transaction by hash, with action details included.
   - **GET /actions**: Query specific actions, filtering by type or related address.

   **Sample Endpoint Implementation**:
   ```go
   func GetBlockByHeight(c *gin.Context) {
       height := c.Param("height")
       var block Block
       err := db.QueryRow(`SELECT * FROM blocks WHERE block_height = $1`, height).Scan(&block)
       if err != nil {
           c.JSON(http.StatusNotFound, gin.H{"error": "Block not found"})
           return
       }
       c.JSON(http.StatusOK, block)
   }
   ```

### 4. **Implementing Real-Time Indexing & Storage**
   - As each block or transaction arrives, parse the relevant data and insert it into the corresponding tables.
   - Use database triggers or TimescaleDB continuous aggregation views to maintain summaries and accelerate queries on frequently requested data.

**Comment by Developerayo** [comment]
1. Block Details
- Block height
- Block timestamp
- Block hash
- Parent block hash
- State root
2. Transaction Details
- Txn hash
- From/To Address
- Value transferred
- Status
- Used Gas
- Timestamp
- Rewards

**Comment by kpachhai** [comment]
> 1. Block Details
> 
> * Block height
> * Block timestamp
> * Block hash
> * Parent block hash
> * State root
> 
> 2. Transaction Details
> 
> * Txn hash
> * From/To Address
> * Value transferred
> * Status
> * Used Gas
> * Timestamp
> * Rewards

This is all good except the From/To Address and Status. Status doesn't make sense here in this context because the data we get is only after a block is accepted so the status is always going to be "Accepted". If the tx is denied, the tx will fail beforehand. As far as From/To Address, currently for the transfer, we are returning the `SenderBalance` and `ReceiverBalance` after the transfer is done.  In order to include the From/To address, we need to include this in the output of `Transfer` action. And need to do this for every single action we have defined. Let me know if this is something you had in mind or something else? 

Currently, this is the kinda info we are able to get for example for the `CreateAsset` action:
```bash
Received a new block:
Block ID: 29oK3JfAfYQd7ab4DP2ZgeK5UicScbsGujmZRhVLzSx7AE4ZLi
Parent ID: kKYep23YFHZVPQQ5af2Ezky8JoXrvJnuyfRJJwgMVbiEZAPay
Timestamp: 2024-11-06T12:57:19-05:00
Height: 137
State Root: KA1WP9sP9YSrwmi7A3TLoirw19Y1Qm2bgXUeP1Q8Q99onFuWM
Unit Prices: (Bandwidth=100, Compute=100, Storage(Read)=100, Storage(Allocate)=100, Storage(Write)=100)
Transactions: 1
  Transaction 1:
    ID: 2G5kA3tjwYSdWQy21q2Fas7xb1c3hfLsbTBpd7mRew6vFSsTaz
    Sponsor: 00c4cb545f748a28770042f893784ce85b107389004d6a0e0d6d7518eeae1292d9
    Max Fee: 58400
    Actions: 1
      Action 1 Type ID: 4
fee consumed: 0.000074900 NAI
output:  &{AssetAddress:008e64cab130b6817bb523dedc0276e967dde22d23d7e0fcb9517128b4115366af AssetBalance:0 DatasetParentNftAddress:}
```

**Comment by kpachhai** [comment]
This is now done.
